"""The Python SDK against the shared offline-approval conformance vectors.

packages/mcp-schemas/vectors/offline-approval-vectors.json, run section by section the way the
reference harness (packages/sdk/src/offline-vectors.test.ts) runs it; docs/OFFLINE-APPROVAL-SDK.md
defines each section. Reads the COMMITTED file, never a generator. No private key is in the file:
approver keys derive from public seeds (``keyDerivation``) and signatures are made at run time,
because an ``offlineApproval`` case's challenge nonce is generated by the code under test.
"""

import asyncio
import base64
import hashlib
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature, encode_dss_signature

from intyga_sdk import (
    OfflineApprovalOptions,
    approver_anchor,
    create_offline_challenge,
    decode_challenge_envelope,
    decode_signature_envelope,
    encode_signature_envelope,
    parse_trust_anchor_file,
    requirement_for,
    sign_challenge_envelope,
    trust_anchor_approvers,
    use_offline_approval,
    verify_trust_bundle,
)
from intyga_sdk.crypto import _parse_rfc3339

V = json.loads(
    (Path(__file__).parents[1] / "vectors" / "offline-approval-vectors.json").read_text(
        encoding="utf-8"
    )
)

P256_N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551


def key_from_seed(seed):
    """keyDerivation: d = (uint256_be(SHA-256(utf8(seed))) mod (n - 1)) + 1."""
    h = int.from_bytes(hashlib.sha256(seed.encode("utf-8")).digest(), "big")
    return ec.derive_private_key((h % (P256_N - 1)) + 1, ec.SECP256R1())


def person(pid):
    return V["people"][pid]


def key_of(pid, kind):
    return person(pid)["keys"][kind]


def sign(pid, kind, payload):
    """ES256 over the UTF-8 payload, IEEE P1363 (r||s), base64."""
    der = key_from_seed(key_of(pid, kind)["seed"]).sign(payload.encode("utf-8"), ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    return base64.b64encode(r.to_bytes(32, "big") + s.to_bytes(32, "big")).decode("ascii")


def at(ts):
    parsed = _parse_rfc3339(ts)
    assert parsed is not None, ts
    return parsed


class TestOfflineApprovalVectors(unittest.TestCase):
    def test_derives_every_published_key_from_its_seed(self):
        for pid, p in V["people"].items():
            for kind, k in p["keys"].items():
                spki = key_from_seed(k["seed"]).public_key().public_bytes(
                    serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
                )
                self.assertEqual(base64.b64encode(spki).decode("ascii"), k["spki"], f"{pid}/{kind}")

    def test_trust_bundle(self):
        for c in V["trustBundle"]:
            with self.subTest(c["name"]):
                # A case may pin its own key (e.g. a non-RSA one); otherwise the top-level key.
                jwk = c["gatewayJwk"] if "gatewayJwk" in c else V["gatewayJwk"]
                r = verify_trust_bundle(c["jws"], jwk, as_of=at(c["asOf"]))
                self.assertEqual(r["ok"], c["ok"], f"{c['name']}: {r.get('reason')}")
                if c["ok"]:
                    self.assertEqual(r["bundle"], c["bundle"])

    def test_bundle_anchor(self):
        for i, c in enumerate(V["bundleAnchor"]):
            with self.subTest(i=i, purpose=c["purpose"], limit=c["limitToDids"]):
                anchor = approver_anchor(V["bundle"], c["limitToDids"], c["purpose"])
                self.assertEqual(anchor["dids"], c["expect"]["dids"])
                for did, keys in c["expect"]["keys"].items():
                    self.assertEqual(anchor["resolveKey"](did), keys, did)

    def test_requirement_for(self):
        for c in V["requirementFor"]:
            with self.subTest(c["name"]):
                bundle = {**V["bundle"], "policy": c["policy"], "unmatchedActionPolicy": c["unmatchedActionPolicy"]}
                self.assertEqual(requirement_for(bundle, c["actionType"], c["display"]), c["expect"])

    def test_trust_anchor_file(self):
        for c in V["trustAnchorFile"]:
            with self.subTest(c["name"]):
                got = None
                try:
                    parsed = parse_trust_anchor_file(c["text"], purpose=c["purpose"])
                    anchor = trust_anchor_approvers(parsed)
                    got = {
                        "purpose": parsed["purpose"],
                        "epoch": parsed["epoch"],
                        "dids": anchor["dids"],
                        "keys": {d: anchor["resolveKey"](d) for d in anchor["dids"]},
                    }
                except ValueError:
                    pass  # refused
                self.assertEqual(got is not None, c["ok"])
                if c["ok"]:
                    self.assertEqual(got, c["expect"])

    def test_create_challenge(self):
        for c in V["createChallenge"]:
            with self.subTest(c["name"]):
                inp = dict(c["input"])
                delegation = inp.pop("delegation", None)
                as_of = at(inp.pop("asOf"))
                kwargs = {
                    "target": inp.pop("target"),
                    "action_type": inp.pop("actionType"),
                    "display": inp.pop("display"),
                    "params": inp.pop("params"),
                    "requester": inp.pop("requester"),
                }
                if "windowMinutes" in inp:
                    kwargs["window_minutes"] = inp.pop("windowMinutes")
                if "nonce" in inp:
                    kwargs["nonce"] = inp.pop("nonce")
                self.assertEqual(inp, {}, "the harness must pass every vector input")
                if delegation is not None:
                    kwargs["delegation"] = {
                        **delegation,
                        "target": kwargs["target"],
                        "actionType": kwargs["action_type"],
                        "params": kwargs["params"],
                        "signers": [],
                    }
                r = create_offline_challenge(bundle=V["bundle"], as_of=as_of, **kwargs)
                self.assertEqual(r["ok"], c["ok"], f"{c['name']}: {r.get('reason')}")
                if not c["ok"]:
                    continue
                for field, want in c["expect"].items():
                    self.assertEqual(r["challenge"][field], want, f"{c['name']}.{field}")

    def test_challenge_envelope(self):
        for c in V["challengeEnvelope"]:
            with self.subTest(c["name"]):
                r = decode_challenge_envelope(c["envelope"])
                self.assertEqual(r["ok"], c["ok"], f"{c['name']}: {r.get('reason')}")
                if c["ok"]:
                    self.assertEqual(r["challenge"], c["expect"])

    def test_signature_envelope(self):
        for c in V["signatureEnvelope"]["encode"]:
            self.assertEqual(encode_signature_envelope(c["witness"]), c["envelope"])
        for c in V["signatureEnvelope"]["decode"]:
            with self.subTest(c["name"]):
                r = decode_signature_envelope(c["envelope"])
                self.assertEqual(r["ok"], c["ok"], c["name"])
                if c["ok"]:
                    self.assertEqual(r["witness"], c["witness"])

    def test_sign_challenge(self):
        for c in V["signChallenge"]:
            with self.subTest(c["name"]):
                r = sign_challenge_envelope(
                    c["envelope"],
                    private_key=key_from_seed(key_of(c["signer"]["person"], c["signer"]["key"])["seed"]),
                    signer_did=c["signerDid"],
                    as_of=at(c["asOf"]),
                )
                self.assertEqual(r["ok"], c["ok"], f"{c['name']}: {r.get('reason')}")
                if not c["ok"]:
                    continue
                w = decode_signature_envelope(r["envelope"])["witness"]
                self.assertEqual(w["signerDid"], c["expect"]["signerDid"])
                self.assertEqual(w["signerPublicKey"], c["expect"]["signerPublicKey"])
                self.assertEqual(w["sigAlg"], c["expect"]["sigAlg"])
                payload = decode_challenge_envelope(c["envelope"])["challenge"]["canonicalPayload"]
                pub = serialization.load_der_public_key(base64.b64decode(c["expect"]["signerPublicKey"]))
                raw = base64.b64decode(w["signature"])
                self.assertEqual(len(raw), 64, "IEEE P1363 r||s")
                # Raises InvalidSignature on failure.
                pub.verify(
                    encode_dss_signature(int.from_bytes(raw[:32], "big"), int.from_bytes(raw[32:], "big")),
                    payload.encode("utf-8"),
                    ec.ECDSA(hashes.SHA256()),
                )

    def test_offline_approval(self):
        scratch = tempfile.mkdtemp(prefix="intyga-offline-vectors-")
        try:
            for c in V["offlineApproval"]:
                with self.subTest(c["name"]):
                    case_dir = tempfile.mkdtemp(prefix="case-", dir=scratch)
                    with open(os.path.join(case_dir, "trust-bundle.jws"), "w", encoding="utf-8") as f:
                        f.write(V["bundleJws"])
                    with open(os.path.join(case_dir, "gateway-key.jwk.json"), "w", encoding="utf-8") as f:
                        f.write(json.dumps(V["gatewayJwk"], separators=(",", ":")))
                    delegation_dir = None
                    if c.get("delegation"):
                        delegation_dir = os.path.join(case_dir, "delegations")
                        os.mkdir(delegation_dir)
                        with open(
                            os.path.join(delegation_dir, f"{c['delegation']}.json"), "w", encoding="utf-8"
                        ) as f:
                            f.write(json.dumps(V["delegations"][c["delegation"]], ensure_ascii=False))

                    def collect(challenge, signers=c["signers"]):
                        out = []
                        for s in signers:
                            if "raw" in s:
                                out.append(s["raw"])
                                continue
                            out.append(
                                encode_signature_envelope(
                                    {
                                        "signerDid": person(s.get("claimDid") or s["person"])["did"],
                                        "signerPublicKey": key_of(s["person"], s["key"])["spki"],
                                        "signature": sign(s["person"], s["key"], challenge["canonicalPayload"]),
                                        "sigAlg": "ES256",
                                    }
                                )
                            )
                        return out

                    r = asyncio.run(
                        use_offline_approval(
                            c["action"],
                            OfflineApprovalOptions(
                                bundle_dir=case_dir,
                                delegation_dir=delegation_dir,
                                requester_did=V["requesterDid"],
                                as_of=at(c["asOf"]),
                                warn=lambda _m: None,
                                collect_signatures=collect,
                            ),
                        )
                    )
                    self.assertEqual(r["ok"], c["ok"], f"{c['name']}: {r.get('reason')}")
                    if not c["ok"]:
                        continue
                    self.assertEqual(sorted(r["signers"]), c["expect"]["signers"])
                    self.assertEqual(r["viaDelegation"], c["expect"]["viaDelegation"])
        finally:
            shutil.rmtree(scratch, ignore_errors=True)

    def test_every_section_is_exercised(self):
        """A section added to the vectors without a runner here must fail, not pass silently."""
        sections = {
            "trustBundle",
            "bundleAnchor",
            "requirementFor",
            "trustAnchorFile",
            "createChallenge",
            "challengeEnvelope",
            "signatureEnvelope",
            "signChallenge",
            "offlineApproval",
        }
        data = {"version", "generated", "note", "keyDerivation", "people", "gatewayJwk", "bundle",
                "bundleJws", "delegations", "requesterDid"}
        self.assertEqual(set(V) - data, sections)


if __name__ == "__main__":
    unittest.main()
